/**
 * Scene Graph Metadata Registry for Akari Digital Twin Engine
 */

export const SCENE_GRAPH = {
  'building.l1': {
    id: 'building.l1',
    name: 'Level 1 — Main Lobby & Security',
    type: 'Floor / Reception',
    status: 'Operational',
    occupancy: 18,
    maxCapacity: 50,
    temperature: 21.5,
    lastMaintenance: '2026-07-10',
    description: 'Visitor reception, automated security turnstiles, and main lobby access logging.',
    hvacUnit: 'Chiller-01',
  },
  'building.l2': {
    id: 'building.l2',
    name: 'Level 2 — Engineering & NOC Center',
    type: 'Operations Center',
    status: 'Optimal',
    occupancy: 34,
    maxCapacity: 40,
    temperature: 19.8,
    lastMaintenance: '2026-06-24',
    description: 'Network operations center, server racks, network fiber distribution & IoT gateways.',
    hvacUnit: 'Chiller-02 (Precision Air)',
  },
  'building.l3': {
    id: 'building.l3',
    name: 'Level 3 — AI & Executive Suite',
    type: 'Executive / Compute',
    status: 'Optimal',
    occupancy: 22,
    maxCapacity: 30,
    temperature: 22.1,
    lastMaintenance: '2026-07-02',
    description: 'AI model compute cluster control room & executive briefing conference suite.',
    hvacUnit: 'Chiller-03',
  },
  'building.roof': {
    id: 'building.roof',
    name: 'Rooftop — Solar Array & Helipad',
    type: 'Renewable Power / Transport',
    status: 'Generating (9.4 kW)',
    occupancy: 0,
    maxCapacity: 10,
    temperature: 24.8,
    lastMaintenance: '2026-07-18',
    description: '450W Monocrystalline PV solar panel array, inverter station & emergency helipad.',
    hvacUnit: 'Roof Exhaust Vents 1-4',
  },
  'hotspot.lobby': {
    id: 'hotspot.lobby',
    name: 'Main Lobby Visitor Desk',
    type: 'Access Control',
    status: 'Armed & Secured',
    temperature: 21.5,
    lastMaintenance: '2026-07-15',
    description: 'Biometric visitor check-in kiosk & security barrier camera system.',
  },
  'hotspot.ops': {
    id: 'hotspot.ops',
    name: 'NOC Server Rack Enclosure',
    type: 'Infrastructure',
    status: 'Optimal (19.8 °C)',
    temperature: 19.8,
    lastMaintenance: '2026-07-01',
    description: 'Tier-3 data center rack enclosure with automated FM200 fire suppression.',
  },
  'hotspot.ai-hub': {
    id: 'hotspot.ai-hub',
    name: 'AI Compute Cluster Node',
    type: 'High Performance Compute',
    status: 'High Load (88% GPU)',
    temperature: 22.1,
    lastMaintenance: '2026-06-30',
    description: 'NVIDIA H100 GPU cluster rack with liquid cooling telemetry.',
  },
  'hotspot.solar': {
    id: 'hotspot.solar',
    name: 'Solar Panel Array Inverter',
    type: 'Power Distribution',
    status: '9.4 kW Active Output',
    temperature: 29.2,
    lastMaintenance: '2026-07-18',
    description: 'DC-to-AC smart inverter array feeding grid peak shaving battery system.',
  },
}
